lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%jwt_private_key_path%'
    public_key_path: '%kernel.project_dir%/%jwt_public_key_path%'
    pass_phrase: '%jwt_passphrase%'
    token_ttl: 86400
