version: '3'

services:
    app:
        # Use a static website hosting service in production
        # See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
        build: .
#        command: npm run dev
        volumes:
            - ./:/usr/src/app:rw,cached
            - /usr/src/app/node_modules
