services:
    Nvision\SpanishCowAdapter\Client:
        arguments:
            $baseUrl: ~
            $username: ~
            $password: ~
            $project: ~

    Nvision\SpanishCowAdapter\SpanishCow:
        arguments:
            $client: ~
            $domains: []